name = "ethsig"
type = "javascript"
workers_dev = true
compatibility_date = "2022-01-26"
kv_namespaces = [
         { binding = "AUTHENTICATION", preview_id = "671d647da83f4e6f8c0ab54c5d3667ae", id = "b086e622446b48ac8a70a35014c35620" }
]

[vars]
WORKERS_RS_VERSION = "0.0.7"

[build]
command = "cargo install -q worker-build && worker-build --release" # required

[build.upload]
dir    = "build/worker"
format = "modules"
main   = "./shim.mjs"

[[build.upload.rules]]
globs = ["**/*.wasm"]
type  = "CompiledWasm"


